"""init

Revision ID: 93daa00d4c17
Revises: 
Create Date: 2024-01-23 20:06:16.799006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "93daa00d4c17"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("sid", sa.Uuid(), nullable=False),
        sa.Column("tg_id", sa.String(), nullable=False, comment="Telegram ID of user"),
        sa.Column("name", sa.String(), nullable=False, comment="Telegram name of user"),
        sa.Column("email", sa.String(), nullable=True, comment="Email of user"),
        sa.Column(
            "phone", sa.String(), nullable=True, comment="Telegram phone number of user"
        ),
        sa.Column(
            "hashed_password",
            sa.String(),
            nullable=True,
            comment="Hashed password of user",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Active status of user"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="DateTime of create record",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="DateTime of update record",
        ),
        sa.PrimaryKeyConstraint("sid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
        schema="users",
        comment="Table with all users",
    )
    op.create_index(
        op.f("ix_users_user_sid"), "user", ["sid"], unique=True, schema="users"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_user_sid"), table_name="user", schema="users")
    op.drop_table("user", schema="users")
    # ### end Alembic commands ###
