version: "3.8"

volumes:
  postgres-data:
  redis-data:

networks:
  net:

services:
  postgres:
    container_name: postgres-template
    image: postgres:15
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5430:5432"
    networks:
      - net

  redis:
    container_name: redis-template
    image: redis/redis-stack:6.2.6-v9
    env_file:
      - ../.env
    volumes:
      - redis-data:/data
    restart: on-failure
    ports:
      - "6377:6379"
      - "8010:8001"
    networks:
      - net
